# Generated by Django 6.0 on 2025-12-18 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('path', models.CharField(help_text='URL path to match (prefix or exact)', max_length=300)),
                ('prefix', models.BooleanField(default=True, help_text='If true, match path prefix')),
                ('allowed_roles', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='page_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
